# Generated by Django 4.2.6 on 2024-11-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mahasiswa',
            fields=[
                ('nim', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('fakultas', models.CharField(max_length=50)),
                ('jurusan', models.CharField(max_length=20)),
                ('no_hp', models.CharField(max_length=15)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_code/')),
                ('last_out', models.JSONField(default=list)),
                ('screenshots', models.JSONField(default=list)),
            ],
        ),
    ]
