# Generated by Django 4.2.6 on 2024-11-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_parkir', '0002_mahasiswa_merk_kendaraan_mahasiswa_plat_nomor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='no_hp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='plat_nomor',
            field=models.CharField(default='Tidak Ada', max_length=20),
        ),
    ]
